class EGVAR(Gear,Presets_BLUFOR) {
    displayName = "Blufor Gear Presets";
    collapsed = 1;
    class Attributes {
        class EGVAR(Gear,ACE_Arsenal_GearPresets_BLUFOR) {
            property = QEGVAR(Gear,ACE_Arsenal_GearPresets_BLUFOR);
            displayName = "Gear Presets";
            tooltip = "";
            control = QEGVAR(Gear,PresetsCombo_BLUFOR);
            typeName = "STRING";
            expression = SCENARIO_EXPRESSION;
            defaultValue = "'None'";
        };
    };
};

class EGVAR(Gear,ACE_Arsenal_Blufor) {
    displayName = "Blufor ACE Gear Settings";
    collapsed = 1;
    class Attributes {
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,SQL);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,TL);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,RFL);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,RFLAT);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,AR);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,GRN);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,VCRW);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,VCMD);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,OFF);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,TWOIC);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,MED);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,AT);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,AAT);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,MG);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,AMG);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,MKS);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,RTO);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,FAC);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,FO);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,ENG);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,EOD);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,HAT);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,AHAT);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,MORTL);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,MOR);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,APLT);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,ACRW);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,CUS1);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,CUS2);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,CUS3);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,CUS4);
        UO_FW_GEAR_TYPECONFIG_ACEAR(Blufor,CUS5);
    };
};
class EGVAR(Gear,Olsen_Blufor) {
    displayName = "Blufor Olsen Gear Settings";
    collapsed = 1;
    class Attributes {
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,SQL);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,TL);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,RFL);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,RFLAT);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,AR);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,GRN);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,VCRW);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,VCMD);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,OFF);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,TWOIC);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,MED);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,AT);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,AAT);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,MG);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,AMG);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,MKS);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,RTO);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,FAC);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,FO);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,ENG);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,EOD);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,HAT);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,AHAT);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,MORTL);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,MOR);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,APLT);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,ACRW);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,CUS1);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,CUS2);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,CUS3);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,CUS4);
        UO_FW_GEAR_TYPECONFIG_OLSEN(Blufor,CUS5);
    };
};
