#include "BracketFiremission\cfgFunctions"
#include "DonutFiremission\cfgFunctions"
#include "GridSpottingFiremission\cfgFunctions"
#include "LineFiremission\cfgFunctions"
#include "MarkerFiremission\cfgFunctions"
#include "PointFiremission\cfgFunctions"
#include "PolarFiremission\cfgFunctions"
#include "PolarSpottingFiremission\cfgFunctions"
class UO_FW_Firemission
{
	file = "x\UO_FW\addons\main\FiremissionModule\Global\cfgFunctions\common";
	class StopArtilleryClient{};
    class AddEventHandler{};
    class ArtGetFireRate{};
    class ArtGetFireRatesqf
    class ArtLoadAviableArtilleries{};
    class ArtMakePlayerObserver{};
    class ArtSetArtillery{};
    class BracketFiremission{};
    class CurtainFiremission{};
    class DonutFiremission{};
    class DynamicMarkerFiremission{};
    class FindMarkerOnMap{};
    class GetAmmoDisplayNameAndIndex{};
    class GetAmmoDisplayNameAndIndexFormated{};
    class GetArtillerySkill{};
    class GetArtyAimTime{};
    class GetArtyAmmo{};
    class GetArtyCalcTime{};
    class GetArtyCaller{};
    class GetArtyCallerText{};
    class GetArtyDisplayName{};
    class GetArtyEta{};
    class GetArtyFiremissionRoundsRequired{};
    class GetArtyIndexAmmoClassname{};
    class GetBracketFiremissionText{};
    class GetCompleteInfoText{};
    class GetCurtainFiremissionText{};
    class GetDonutFiremissionText{};
    class GetGridSpottingFiremissionText{};
    class GetLineFiremissionText{};
    class GetMarkerFiremissionText{};
    class GetNewAccuracy{};
    class GetObserverSkill{};
    class GetPointFiremissionText{};
    class GetPolarFiremissionText{};
    class GetPolarSpottingFiremissionText{};
    class GridSpottingFiremission{};
    class initLoadArtilleryData{postInit = 1};
    class initPlayerFO{};
    class InputIsNumber{};
    class InputIsUnit{};
    class InternalFiremission{};
    class InternalRepackArtilleryMagazines{};
    class InternalSpottingFiremission{};
    class IsArtyAviable{};
    class LineFiremission{};
    class MarkerFiremission{};
    class PointFiremission{};
    class PointMarkerFiremission{};
    class PolarFiremission{};
    class PolarSpottingFiremission{};
    class RegisterForwardObserver{};
    class SendArtyHint{};
    class SendArtyHintGlobal{};
    class SetArtilleryData{};
    class SetArtyAviable{};
    class SetArtyCaller{};
    class SetArtyFiremissionRoundsRequired{};
    class SetArtyReadyStatus{};
    class SetObserverSkill{};
    class StopArtillery{};
};