class UO_Framework_AI {
    tag = "UO_FW_AI";
    class UO_FW_AI_Common {
        file = "x\UO_FW\addons\Main\HeadlessAIModule\cfgFunctions\common";
        class init { scope = 1;};
        class deleteVehicles {scope = 1;};
        class enableZones {scope = 1;};
        class monitor {scope = 1;};
        class playAnimation {scope = 1;};
        class removeKit {scope = 1;};
        class setup {scope = 1;};
    };
    class UO_FW_AI_Check {
        file = "x\UO_FW\addons\Main\HeadlessAIModule\cfgFunctions\check";
        class checkManualPos {scope = 1;};
        class checkNearbyAll {scope = 1;};
        class checkNearbyPlayer {scope = 1;};
        class checkStance {scope = 1;};
        class checkifHC { scope = 1;};
    };
    class UO_FW_AI_Create {
        file = "x\UO_FW\addons\Main\HeadlessAIModule\cfgFunctions\create";
        class createAction {scope = 1;};
        class createFunctions {scope = 1;};
        class createGroup {scope = 1;};
        class createGroupInit {scope = 1;};
        class createOccupyGroup {scope = 1;};
        class createOccupyGroupInit {scope = 1;};
        class createUnit {scope = 1;};
        class createVehicle {scope = 1;};
        class createWaypoint {scope = 1;};
        class createWaypointModified {scope = 1;};
        class createWaypoints {scope = 1;};
        class createZone {scope = 1;};
        class createZoneInit {scope = 1;};
    };
    class UO_FW_AI_Debug {
        file = "x\UO_FW\addons\Main\HeadlessAIModule\cfgFunctions\debug";
        class debugSyncedModules {scope = 1;};
        class debugCreateMarker {scope = 1;};
    };
    class UO_FW_AI_Get {
        file = "x\UO_FW\addons\Main\HeadlessAIModule\cfgFunctions\get";
        class getBuildingList {scope = 1;};
        class getBuildings {scope = 1;};
        class getGroupVariables {scope = 1;};
        class getInjuredSound {scope = 1;};
        class getKnockDownAnimation {scope = 1;};
        class getNearestBuilding {scope = 1;};
        class getNearestBuildings {scope = 1;};
        class getNearestGroupBuildings {scope = 1;};
        class getNewPos {scope = 1;};
        class getRandomBuilding {scope = 1;};
        class getRandomBuildings {scope = 1;};
        class getRandomGroupBuildings {scope = 1;};
        class getDetails {scope = 1;};
        class getDetailsArray {scope = 1;};
        class getDetailsGroup {scope = 1;};
        class getDetailsThing {scope = 1;};
        class getDetailsVehicle {scope = 1;};
        class getDetailsVehicleEmpty {scope = 1;};
        class getDetailsUnit {scope = 1;};
        class getRandomPositionCircle {scope = 1;};
        class getSafePos {scope = 1;};
        class getSide {scope = 1;};
        class getStartBuilding {scope = 1;};
        class getSynced {scope = 1;};
        class getSyncedGroups {scope = 1;};
        class getSyncedModules {scope = 1;};
        class getSyncedObjects {scope = 1;};
        class getSyncedObjectsTemplate {scope = 1;};
        class getSyncedRespawns {scope = 1;};
        class getTasks {scope = 1;};
        class getTaskParams {scope = 1;};
        class getTurrets {scope = 1;};
        class getWaypointDetails {scope = 1;};
        class getVehicleRoles {scope = 1;};
    };
    class UO_FW_AI_Modules {
        file = "x\UO_FW\addons\Main\HeadlessAIModule\cfgFunctions\modules";
        class control {scope = 1;};
        class module {scope = 1;};
        class position {scope = 1;};
        class respawn {scope = 1;};
        class task {scope = 1;};
        class temp {scope = 1;};
        class zone {scope = 1;};
    };
    class UO_FW_AI_Set {
        file = "x\UO_FW\addons\Main\HeadlessAIModule\cfgFunctions\set";
        class setAssignedVehicle {scope = 1;};
        class setBuildingPos {scope = 1;};
        class setCaptive {scope = 1;};
        class setCombatant {scope = 1;};
        class setCompletedTasks {scope = 1;};
        class setFlashlights {scope = 1;};
        class setGroupBehaviour {scope = 1;};
        class setGroupVariables {scope = 1;};
        class setMarkerPos {scope = 1;};
        class setMultiOccupy {scope = 1;};
        class setPersistent {scope = 1;};
        class setRadial {scope = 1;};
        class setRespawn {scope = 1;};
        class setStance {scope = 1;};
        class setSurrender {scope = 1;};
        class setTracker {scope = 1;};
        class setVehicle {scope = 1;};
        class setZone {scope = 1;};
    };
    class UO_FW_AI_Task {
        file = "x\UO_FW\addons\Main\HeadlessAIModule\cfgFunctions\task";
        class taskActivate {scope = 1;};
        class taskAssign {scope = 1;};
        class taskCheck {scope = 1;};
        class taskComplete {scope = 1;};
        class taskForceFire {scope = 1;};
        class taskForceHold {scope = 1;};
        class taskGroup {scope = 1;};
        class taskLoiter {scope = 1;};
        class taskHoldUntil {scope = 1;};
        class taskInit {scope = 1;};
        class taskBuildingPatrol {scope = 1;};
        class taskBuildingDefend {scope = 1;};
        class taskMonitor {scope = 1;};
        class taskMoveBuilding {scope = 1;};
        class taskMoveBuildings {scope = 1;};
        class taskMoveGroupBuildingsDefend {scope = 1;};
        class taskMoveGroupBuildingsPatrol {scope = 1;};
        class taskMoveMultipleBuildingsDefend {scope = 1;};
        class taskMoveMultipleBuildingsPatrol {scope = 1;};
        class taskMoveNearestBuildingDefend {scope = 1;};
        class taskMoveNearestBuildingPatrol {scope = 1;};
        class taskMoveRandomBuildingDefend {scope = 1;};
        class taskMoveRandomBuildingPatrol {scope = 1;};
        class taskMoveRandomGroupBuildingsDefend {scope = 1;};
        class taskMoveRandomGroupBuildingsPatrol {scope = 1;};
        class taskMoveRandomMultipleBuildingsDefend {scope = 1;};
        class taskMoveRandomMultipleBuildingsPatrol {scope = 1;};
        class taskRegister {scope = 1;};
        class taskRemoveZoneActivated {scope = 1;};
        class taskSearchNearby {scope = 1;};
        class taskSet {scope = 1;};
        class taskSetBunker {scope = 1;};
        class taskSentry {scope = 1;};
        class taskPlacement {scope = 1;};
        class taskPatrol {scope = 1;};
        class taskPatrolPerimeter {scope = 1;};
    };
    class UO_FW_AI_Main {
        file = "x\UO_FW\addons\Main\HeadlessAIModule\cfgFunctions\Main";
        class ActiveHandler {scope = 1;};
        class GroupHandler {scope = 1;};
        class initMain {scope = 1;};
        class QueueHandle {scope = 1;};
    };
    class UO_FW_AI_Misc {
        file = "x\UO_FW\addons\Main\HeadlessAIModule\cfgFunctions\Misc";
        class playerInit {scope = 1;};
    };
    class UO_FW_AI_Diag {
        file = "x\UO_FW\addons\Main\HeadlessAIModule\cfgFunctions\Diag";
        class AIHit {scope = 1;};
        class AttachPosition {scope = 1;};
        class BuildingCheck {scope = 1;};
        class BuildingSpawnCheck {scope = 1;};
        class CheckStatic {scope = 1;};
        class Classvehicle {scope = 1;};
        class ClosestEnemy {scope = 1;};
        class ClosestObject {scope = 1;};
        class DriverCheck {scope = 1;};
        class EnemyArray {scope = 1;};
        class HasMine {scope = 1;};
        class HasRadioGroup {scope = 1;};
        class IRCheck {scope = 1;};
        class LOSCheck {scope = 1;};
        class MapMarkers {scope = 1;};
        class NearEnemies {scope = 1;};
        class searchNestedArray {scope = 1;};
        class StanceModifier {scope = 1;};
        class UnitCheck {scope = 1;};
        class VehicleHandle {scope = 1;};
        class Waypointcheck {scope = 1;};
        class WepSupCheck {scope = 1;};
    };
    class UO_FW_AI_Danger {
        file = "x\UO_FW\addons\Main\HeadlessAIModule\cfgFunctions\dangercauses";
        class CombatMovement {scope = 1;};
        class CurrentStance {scope = 1;};
        class DeadBodyDetection {scope = 1;};
        class ExplosionDetection {scope = 1;};
        class MoveToCoverGroup {scope = 1;};
        class RecentEnemyDetected {scope = 1;};
        class SetCombatStance {scope = 1;};
        class stopToShoot {scope = 1;};
        class VehicleHandleDanger {scope = 1;};
    };
    class UO_FW_AI_Combat {
        file = "x\UO_FW\addons\Main\HeadlessAIModule\cfgFunctions\combat";
        class ArmEmptyStatic {scope = 1;};
        class CombatAttack {scope = 1;};
        class CombatDefend {scope = 1;};
        class CombatMode {scope = 1;};
        class CombatMoveTo {scope = 1;};
        class CombatResponse {scope = 1;};
        class DestroyBuilding {scope = 1;};
        class FindCoverPos {scope = 1;};
        class FlankManeuver {scope = 1;};
        class FocusedAccuracy {scope = 1;};
        class ForceHeal {scope = 1;};
        class FormationChange {scope = 1;};
        class FragmentMove {scope = 1;};
        class LoiterAction {scope = 1;};
        class MoveInCombat {scope = 1;};
        class MoveToCover {scope = 1;};
        class PlaceMine {scope = 1;};
        class RadioCommsEnemy {scope = 1;};
        class RearmGo {scope = 1;};
        class RearmSelf {scope = 1;};
        class ReGroup {scope = 1;};
        class SightAid {scope = 1;};
        class SuppressingShots {scope = 1;};
        class ThrowGrenade {scope = 1;};
        class WatchEnemy {scope = 1;};
    };
};
