#include "cfgAttributes\External.hpp"
#include "cfgAttributes\Main\MissionTypeAttribute.hpp"
#include "cfgAttributes\Main\TeamTypeAttribute.hpp"
#include "cfgAttributes\Main\RespawnTypeAttribute.hpp"
#include "cfgAttributes\JiP\JipTypeAttribute.hpp"
#include "cfgAttributes\EndConditions\ExtractionTeamAttribute.hpp"
#include "cfgAttributes\EndConditions\EndConditionModeAttribute.hpp"
#include "cfgAttributes\EndConditions\EndConditionsCaptureZoneTeamAttribute.hpp"
