////////////////////////////////////////////////////////
// GUI EDITOR OUTPUT START (by Sacher, v1.063, #Dyroxu)
////////////////////////////////////////////////////////

#define ARTIWIDTHMAINSPACE  0.25
#define ARTIHEIGHTMAINSPACE  0.15
#define ARTILAYOUTHEIGHT   0.05
#define ARTILAYOUTHEIGHTSPACE   0.055
#define ARTIBORDERTHICKNESS   0.01
#define ARTILAYOUTWIDTH   0.15
#define ARTILAYOUTWIDTHSPACE   0.16

#define POFM_DIA_IDD_DISPLAY 11772
#define POFM_DIA_IDC_GUNSELECT 39395
#define POFM_DIA_IDC_SHELLSELECT 39396
#define POFM_DIA_IDC_GRID 39397
#define POFM_DIA_IDC_MILS 39398
#define POFM_DIA_IDC_DISTANCE 39399
#define POFM_DIA_IDC_DISPERSION 39400
#define POFM_DIA_IDC_BURSTNUMBER 39401
#define POFM_DIA_IDC_BURSTROUNDS 39402
#define POFM_DIA_IDC_BURSTDELAY 39403
#define POFM_DIA_IDC_NUMGUNSELECT 39405
