#define MainPREFIX x
#define PREFIX UO_FW

#define MAJOR 1
#define MINOR 0
#define PATCH 4

#define VERSION MAJOR.MINOR.PATCH
#define VERSION_AR MAJOR,MINOR,PATCH
#define VERSIONSTR QUOTE(VERSION)

#define REQUIRED_VERSION 1.56
